### ISSUE TITLE
CMD/CTRL+Click does nothing when clicking on Hyperlinks

### ISSUE THREAD

**Issue by christianhans** [MaxLap/standard-notes-indent-editor#6]
MacOS 10.15.2
Standard Notes Desktop v3.0.25

**Comment by MaxLap** [comment]
Thanks for the report!

I didn't test the feature on the desktop version... wopsie! I use the browser version only... 

I can see that it indeed doesn't work there. I will look into it.

**Comment by MaxLap** [comment]
This is fixed in the release I just made. (1.4.2) Thanks for the report!

**Comment by christianhans** [comment]
Thanks! Still doesn't seem to work for me. Tried both CMD+Click and CTRL+Click.

**Comment by christianhans** [comment]
Yes, version is 1.4.2. and I did try restarting the App. Issue occurs both on Home and Work Macbook. Chrome DevTools shows no JavaScript errors.

**Comment by MaxLap** [comment]
Did you try using the web SN to ctrl+click the same link? Does it work?

Could you paste me the exact string you have in your note? Maybe the link has something special in it that needs handling.

**Comment by christianhans** [comment]
Tried both CMD and CTRL+Click.

Link is https://www.google.com

Tried also Firefox and Safari - both don't work either.

**Comment by christianhans** [comment]
I also reinstalled the extension to make sure I am up to date.

**Comment by MaxLap** [comment]
Okay, I don't have a Mac, so it's hard to diagnose/fix. But I just did an attempt at a fix, available here: https://maxlap.github.io/standard-notes-indent-editor/demo.html
Can you give that a try?

**Comment by christianhans** [comment]
Yes that works!

Opens the link in background on Safari/Chrome and in Foreground Tab on Firefox.

**Comment by MaxLap** [comment]
Those sound more like behavior of the browser than thing I have control of.

I released 1.4.3 with the fix. Might take a little while for it to propagate
